### PR TITLE
Fix: Rework vlink icon (again)

### LINKED ISSUE #204: Demarcation indented on multiline phrases
`.vlink span` got a `padding-left 1.5em` which is applied to every line,

Looked into `::first-line` but is only supported on block elements

screen shot 2019-01-16 at 5 18 08 pm

### PR DESCRIPTION
**Pull request by lukeed**
More reliable alignment – borrows @gwil's spacing trick (on the main parent). Pixel alignment better across different font sizings too.

Pinging @eudisd to double-check Dashboard version. I think I updated everything necessary

---

Closes #204

### CODE REVIEW

**Comment by gwil** [comment]
This one is hard to visualize because the test page doesn't have multiline links, but this is what i'm seeing with my viewport around 250-290px:

screen shot 2019-01-16 at 8 10 12 pm

Also removed the `box-shadow` because of the overlap here:
screen shot 2019-01-16 at 8 08 22 pm

**Comment by lukeed** [comment]
Okay, I'll play with it some more. If we wanna keep the shadow, can put a zindex on the img

**Comment by lukeed** [comment]
@gwil This version fixes those issues. The test site looks good, but when I dumped it into one of the demo sites, the publisher fonts/lineheights altered the positioning of the demarcation lip 😠 

Will revisit tomorrow some more.

I have local, unpushed changes that get it closer (same method, different values) but it's still off.... either the test simple works, or the demo site works.

**Comment by eudisd** [comment]
Tested this locally and noticed a very slight misadjustment with the icon.  It seems to be shifted up 1px or so higher than the vlink itself:

image

**Comment by eudisd** [comment]
Btw, looks good on dashboard: 

screen shot 2019-01-17 at 12 37 40 pm

**Comment by eudisd** [comment]
Lastly, there is a bit of overlap with the vlinks.  Not sure if it's an issue or not:

screen shot 2019-01-17 at 12 39 24 pm

**Comment by lukeed** [comment]
This PR is being superceded by #206 thanks for checking in though 🙏

**Pull request closed without merging**
