### PR TITLE
Scale Rectangle View Correctly

### LINKED ISSUE #174: Use Fixed (Percentage-Based) Padding For Expanded View Instead of Scaling
Original Comment
> Rectangle video has too much padding on left and right side in expanded view

### PR DESCRIPTION
**Pull request by eudisd**
Closes #174, #175

### CODE REVIEW

**Comment by gwil** [comment]
Tested and LGTM! https://dist-jzxbwepuvf.now.sh

**Comment by lukeed** [comment]
Can we fix this once & for all in all shapes? See below, tested with Garrett's link

Viewport: 1470 x 889

screen shot 2019-01-15 at 5 33 21 pm
screen shot 2019-01-15 at 5 33 31 pm
screen shot 2019-01-15 at 5 33 15 pm

**Comment by eudisd** [comment]
@lukeed this issue was specifically for the mobile view (flagged by Patrick).  In order for me to adjust the widths of the mac/chrome in a satisfactory way, I would need consensus from everyone involved. ie, I would like to know what widths you, patrick and @gwil all agree with.

That way we dont do a back and forth as to what is the correct widths.  I, for instance, think that the above widths look good.  I dont know how wide  we'd all like the widths to be.

**Comment by eudisd** [comment]
Another thing to note is that, because on desktop we generally view it landscape dimensions (ie width > height), there is a limit as to how wide we go with the widths.  Otherwise, the height will push against other elements (for instance, how high we "pin" the player, and also how much we push down the emoji widget below; in order to keep the correct aspect ratio of the square vs. circle vs. rectangle

**Comment by gwil** [comment]
I can go through and update positioning for all viewport sizes. Will go through it with Luke Goh today for feedback

**Comment by eudisd** [comment]
🙌

**Comment by lukeed** [comment]
Aye, that's fine. I just wanted to address it. @gwil will you be working into this PR, or should I merge this & you get the "unification" in with LG separately?

**Comment by gwil** [comment]
Updated: https://dist-zlskdtlyxh.now.sh

**Comment by lukeed** [comment]
Looks much better on desktop 👌 

Baby iPhone 5 doesn't have the reactions visible at all

**Comment by lukeed** [comment]
Closer~! 😜 Sending screenshots in Slack

**Comment by gwil** [comment]
Tested all the shapes in iPhone 5s both with the navigation bar visible/hidden: https://dist-yimaepwbed.now.sh

`.square` was a little difficult and ended up scaling down the Reactions
simulator screen shot - iphone 5s - 2019-01-16 at 18 28 15

**Comment by eudisd** [comment]
IphoneX, galaxy S3 and iphone6/7/8 are messed up:

image

**Comment by eudisd** [comment]
Created new PR for these fixes here: https://github.com/VIDY/embed.js/pull/208 (based off this branch)

**Comment by eudisd** [comment]
Hey guys, i'd like to merge this in if you guys are cool with it.  We can work on further desktop fixes as part of @gwil's new branch.

**Comment by lukeed** [comment]
Force pushing master cuz this made a terrible mess of log history. @eudisd, we are squash only here. Please reopen PR with same changes.

**Comment by lukeed** [comment]
Also disabled merge commits for the repository

**Pull request merged**
