### PR TITLE
Fix: Position vlink icon correctly for multiline

### PR DESCRIPTION
**Pull request by lukeed**
Simpler alternative – does not pose any of the issues from #205 

Closes #205, #204

### CODE REVIEW

**Comment by gwil** [comment]
Closer but I think the `margin` throws it off on the 2nd line ~!
screen shot 2019-01-17 at 6 56 48 am

**Comment by eudisd** [comment]
Verified that this fixes most of the issues I noted in #205.  The one potential issue still exists in this branch with the **overlaps**.  But like I mentioned in #205, not sure if this qualifies as a bug or not.

**Comment by lukeed** [comment]
Overlaps are okay ever since we moved to lip design. It's dictated by host's lineheight

Will checkout the margin stuff again. Wasn't happening on my end

**Comment by eudisd** [comment]
@gwil are you still seeing the indentation issue you noted above?  If not, I think this is good to go

**Comment by lukeed** [comment]
Here are changes with latest commits. In the desktop shot, you'll see the only lingering issue that I'm seeing (icon can be standalone).

screen shot 2019-01-17 at 11 03 35 am

screen shot 2019-01-17 at 11 08 42 am

**Comment by gwil** [comment]
Looked into the hanging icon but haven't came up with a fix. Probably should come back to it since it's an edge case?

**Comment by lukeed** [comment]
I think I got it /hairpull. Incoming

**Comment by lukeed** [comment]
@gwil for re-review

**Comment by gwil** [comment]
Let's get over this one ~! Thx for the attention to detail 🥇

**Pull request merged**
