### PR TITLE
Browser related debug

### PR DESCRIPTION
**Pull request by gwil**
- Fixes progress indicator on Firefox
- Fixes issue with `isEqualNode` on an object which breaks Microsoft Edge
- Fixes rendering for missing font weights on Firefox/Safari

Demo: https://dist-juxq1wpu9.now.sh/

### CODE REVIEW

**Comment by gwil** [comment]
The `event.target` is not always an `Element` though, it's an Object like `{"input":{}}` or `{"_position":"top"}` which doesn't have the `isEqualNode` method (and breaks in MS Edge)

**Comment by lukeed** [comment]
I'm curious, where does that happen? It looks like these 3 functions are tied to native event handlers

**Comment by gwil** [comment]
Testing on MS Edge 18, I first noticed it on `onExitPlayer` (it breaks the player state and doesn't close)

**Comment by lukeed** [comment]
Odd. That shouldn't happen since that particular function is only called as the `transitionend` handler directly 🤔 

Can merge for now, but should look into this in the future.... even if it means that it's an Edge bug

(I don't access to the browser so can't help debug.)

**Comment by gwil** [comment]
I think the `transitionend` is firing on multiple elements. FWIW i'm testing on Browserstack (credentials in 1password)

**Comment by lukeed** [comment]
Ah, I've never used that. Will have to play with it later.

Yeah, `transitionend` will fire for all of the element's child animations. That's why the `isEqualNode` check was in there.

It's like if you assigned a click handler to a div – it can capture/listen to clicks on its child contents.

---

Another thing that just occurred to me... We can probably do this instead of the `instanceof` check from this PR:

```js
if (ev.target !== vidy) return;
```

**Comment by lukeed** [comment]
Gotcha, thanks 👍

**Comment by lukeed** [comment]
Just dawned on me: What about `vidy.isEqualNode(ev.target)`? haha

Since `vidy` always exists, it gets rid of the reliance on `ev.target` existing. Plus vidy will never equal undefined

**Pull request merged**
