### PR TITLE
Demarcation styling to accommodate line-height

### LINKED ISSUE #137: UI: "Demarcation fixes"
I don't have details for this, but apparent you have screenshots/know what you're doing @gwil 😅 

> ***Original Note:***
> demarcation bugs from all screenshots (the demarcation on larger text or bolder text has spacing inside and surrounding the link off, the vidy icon is too small) lets always make it have the equivalent respective spacing and vidy icon size based on font size. Add a bit more padding on left and right between our default demarcation and also left or right inside our default demarcation between end and last character and first as well

### PR DESCRIPTION
**Pull request by gwil**
Uses Ems instead of pixels to scale icon/demarcation lip to line-height

Before/after:
before
after
Closes #137

### CODE REVIEW

**Comment by gwil** [comment]
Just made some additional edits with PC. Have not yet tried on some try-vidy sites, not easily setup for it but can make a new playground for that

**Comment by lukeed** [comment]
You can copy the newly built CSS and dump it into devtools of a live site and it'll update in place

**Comment by lukeed** [comment]
Are we waiting on this?

**Comment by gwil** [comment]
Ready to go!

**Pull request closed without merging**
