### PR TITLE
Fix Demarcation Bug

### PR DESCRIPTION
**Pull request by eudisd**
Hey @lukeed Not sure the context of the `toLocation` function.  Why do we need a custom indexOf function?

Also if you could verify that this fixes the issue too?  Thanks

## Video
 https://cl.ly/c0b5374aed73

### CODE REVIEW

**Comment by lukeed** [comment]
And this would _not_ fix the bug in the video. This would add more bugs instead.

The jumping-link has to do with sibling node placements & not the text-extraction itself. You'll notice that the correct phrase (the highlighted part) is always extracted correctly. It's just moved to the wrong place.

**Comment by eudisd** [comment]
Thanks for the context explanation.

Not sure what you mean by your last comment though.  The `index` was directly responsible for the node placement in my local debugging.  That's how I tracked it down it. 

In other words, the error I saw was that if text contained a word, `toLocation` would return `-1` erroneously and this would prepend the vidy link to the beginning of the paragraph.  But if it found the word in text correctly (ie `index` is not `-1`) then it correctly places the node.

I will take a second look at this later today

**Comment by lukeed** [comment]
Ah I see that. Yeah substrings at the beginning of the parent string (the text node content) return `-1` instead of 0

I'll take a look too

**Comment by eudisd** [comment]
Sounds good!

**Comment by lukeed** [comment]
Okay, so it wasn't the index/position after all. In my quick test, I was ignoring casing, which _is_ preserved. For example, using the strings from the code snippet above:

```js
util.toLocation(abc, 'hello', 0);
//=> -1   –   because "Hello" only

util.toLocation(abc, 'Hello', 0); // => 0
util.toLocation(abc, 'Hello', 1); // => 31
```

I'm back to this having to do with placement, likely to do with stale references to (text) `node`s.

Can you show me how you saw this:

> I saw was that if text contained a word, toLocation would return -1 erroneously 

When/If this is the case, I think it's because the `node.data` is stale.

**Comment by eudisd** [comment]
Hey @lukeed so if you want we can hope on a call after you get back from your 1-hour thing and I can show you.  But basically, I loaded the local embed.js sdk with console logs at the `$draw` function.  This console.log would output the index after a vidy link is highlighted.  

From the example index.html sdk, I then highlighted the two words that I showed you in the video.  

I noticed that  `node.data.indexOf` returns the correct index (33 I think), while `toLocation(...)` doesn't (it returns -1)

**Pull request closed without merging**
