### PR TITLE
Fix: Prevent `muted` toggle on invisible corners

### LINKED ISSUE #122: Fix: Mask Radius registers Clicks
We've known about this one for a while, but this ticket formalizes it.

I think we can wrap the `vidy__mask` layer (with the volume toggler) in an extra layer, in which _that_ layer has the `overflow:hidden` & shape adjustments.

Need to verify, but IIRC _that_ would prevent the current behavior of the `vidy__mask`'s hidden corners from toggling the volume

### PR DESCRIPTION
**Pull request by lukeed**
Closes #122

### CODE REVIEW

**Comment by eudisd** [comment]
Unfortunately this is still happening 😬 

Video:
https://files.slack.com/files-pri/T2BK57X52-FFB4K0P5H/download/mov_0011.mp4

**Comment by lukeed** [comment]
This is as good as it's gunna get 😞 

Tried:

* Multiple wrapper elements
* `clip-path` on:
  * video
  * sub-wrappers
  * everything
* moving `onclick` to: 
  * mask
  * sub-wrappers
  * video
* `mask`
* `clip` (deprecated, `rect`s only)
* event target delegation (video, mask, or player always hit)

None of these worked on iOS.<br>
Some of these broke Android, Desktops, and/or both.

This is the best

**Comment by eudisd** [comment]
Bummer.  I think fundamentally changing the html structure of this might be the only solution (ie not wrap the video on the mask) Albeit, not sure it makes sense to do this week, since it's a bit involved

**Comment by lukeed** [comment]
How do you mean? I played with additional divs, which changes the markup. At some point we need to have a mask that mutates the visible shape of the video & positions it. 

And, in essence, the issue is that a `div.circle` is not purely a circle. The corners still exist. Having `clip-path` chops them off in browsers that implement correctly, but in iOS's world, a `div.circle` is still a square layer, which means that the _entire_ square will still receive events.

**Comment by eudisd** [comment]
Hmm.  I was alluding to my initial investigations.  I was able to make it work by making `video` a sibling of the mask and setting position: absolute, z-index 1 (for the click handler). then moving the click handler to the video.  Then setting the border-radius on the video itself, (rectangle, square, or circle) instead of having a mask.  This made it go away, but I did not want to change the fundamental html structure.

By the way, this seems to be a general safari issue, not specific to ios.  for example: https://cl.ly/9c0a41b6eef5

**Comment by lukeed** [comment]
Happy to see a PR with that. Pretty sure I've tried that combination

Yeah, iOS Safari & OSX Safari are the same engines

**Comment by lukeed** [comment]
Nah, will wait for yours

**Comment by lukeed** [comment]
Closed via #187

**Pull request closed without merging**
