### PR TITLE
Preload visible Link assets~!

### PR DESCRIPTION
**Pull request by lukeed**
To avoid downloading assets as soon as the `.vlink` is hovered or tapped, this PR now preemptively downloads the assets as soon as the `.vlink` _entirely_ enters the viewport.

A dummy `<video/>` element is created per vidy link, which never gets attached to the DOM. This is enough to send requests for (and then decode) the media.

Ideally, we'd `delete` the dummy video elements but Rollup was throwing errors about strict mode etc etc.

I've also reconfigured some of the `elem._*` references, mostly so that it's all at once / in one place. The `clip.TYPE.url` paths are saved as `elem._poster` and `elem._videosrc` and are used both by the dummy & real video elements.

> I also wanted to `delete` the `clip` reference, since it's hogging a bit of memory, but again, Rollup.

In a future PR, I'd like to change how and when the real `video` gets its `poster` & `src` updated now that the assets are (99.9% likely) already cached.

Video Walkthrough, because I can't ever figure out how to record GIFs well...

https://www.dropbox.com/s/kxyf0yjpoynwajk/vidy-preload.mov?dl=0

### CODE REVIEW

**Comment by lukeed** [comment]
Oh, and new size is `4.75 kB`, up from `4.59 kB`

**Comment by lukeed** [comment]
Rollup didn't like the presence of `delete` anywhere. For now, it's totally fine. The `clip` object will now be GC'd correctly anyway.

I also did some further testing last night to clear this up in my mind – the `video` tag per `.vlink` can't be deleted after all as that destroys the source buffer and defeats the purpose of preload. AKA, we download it, keep it around via the `<video src=HERE">` then tell it to go away/dump it before we try to reuse it.

**Comment by lukeed** [comment]
Gracias 💃

**Comment by eudisd** [comment]
Sounds good.  Leaving the links in there makes sense 👍

**Pull request merged**
