### PR TITLE
Fix: Prevent force-touch on vlinks on iOS

### LINKED ISSUE #139: Event: Player remains in Hover mode w/o interaction
> ***Original Note:***
> sometimes I can just hold down a few times repeatedly and the vidy bugs out and plays perpetually in small view mode even after I let go

Reported on iOS, but perhaps not limited to iOS.

I suspect https://github.com/VIDY/embed.js/blob/master/src/index.js#L207 is related.

### PR DESCRIPTION
**Pull request by lukeed**
Prevents the behavior as described by @eudisd's instructions in #139 

---

Closes #139

### CODE REVIEW

**Comment by lukeed** [comment]
What are the issues

**Comment by gwil** [comment]
This actually solved the issue when a Vidylink is placed on a `<a>` link as well, so nice fix @lukeed!

**Comment by lukeed** [comment]
@eudisd Tracked that down, was the only way I/we were able to get the player to be in that state

**Comment by eudisd** [comment]
💥

**Pull request merged**
