### PR TITLE
Fix: forcibly hide any non-vlink elements

### PR DESCRIPTION
**Pull request by lukeed**
Uses `visibility: hidden` on anything within the `.vidy` wrapper. This works differently than `pointer-events: none` as it actually _removes_ the layer (same as `display: none`) as opposed to keeping the layer but trying to make it non-interactive.

Current approach couldn't/can't bypass the OS's ability to select text – and there's inconsistency between browsers/platforms in how/what `pointer-events: none` _actually_ prevents.

> As we saw with IE11 – pointer-events actually has no effect there 😆 

***TODO***

- [x] The hover-exit animation needs to be clean up. It is nowhere near as smooth because `visiblity` property isn't (and can't be) transitioned.

---

_Closes #140, #141, #142 _

_And, **I think**, may be a candidate for #140_

**Edit**

Updated related issues

### CODE REVIEW

**Comment by lukeed** [comment]
The only difference between `visibility: hidden` & `display: none` is that visibility still has dimensionality, yes. However, as far as layer visibility/interactivity are concerned, they are the same.

Visibility is used when you don't want to recompute sizing/layout when {thing} becomes visible. Toggling display is used when you don't care about shifting/moving stuff on the page around.

**Comment by lukeed** [comment]
Just pushed more changes, very excited about it 😁 

All "frozen link" issues had to do with the inner SDK elements receiving the touch elements. This is why the login form was being triggered – the reactions triggered the form.

The fix here was to make everything non-interactive once hovering/expanding has shutdown. This is done thru `resetPlayer` since that is our generic/shared cleanup function. It's also added on init. 

The `locked` class is removed once a hovering instance has been decidedly created. 

Expanded state will already ensure that the "hovering" precursor steps (`onHovered`) has been called before it continues. This is only the case when opening a page with a shared URL.

**Comment by eudisd** [comment]
Dope!

**Comment by lukeed** [comment]
🎉 Approval still stands?

**Comment by eudisd** [comment]
Just doing a quick pass one sec...

**Comment by eudisd** [comment]
Found an issue with `removeEventListener` erroring out the page and making it unresponsive.  I don't think this is specific to your branch though, but rather whats on `master`.  II think you should be good to go.

**Pull request merged**
