### PR TITLE
Fix Image Resize and Jitter

### LINKED ISSUE #172: Improve Thumbnail-To-Video Transition
Original comment

> The thumbnail is blinking and jarring right now on initial hold. It’s like it resizes quickly and is the mirror image of the first frame of the actual video. The thumbnail needs to be the exact first frame of the video so its smooth and unnoticeable transition

### PR DESCRIPTION
**Pull request by eudisd**
Closes #196
Closes #172 

Tested

  - desktop/chrome/safari
  - iphone/chrome/safari
  - galaxy S3 simulator
  - iphone 6/7/8 simulator

### CODE REVIEW

**Comment by eudisd** [comment]
Yeah, it was a whole host of issues stemming from it yes.  Was a pain to debug.  took me too long 😩

**Comment by eudisd** [comment]
Also the `translateX` and then doing `left` on the container was the main issue.  Once I removed that, it was all object-fit stuff yeah

**Comment by lukeed** [comment]
>  took me too long 

Hey, you got it. Took me all day to keep two fkin boxes together in #206

**Comment by eudisd** [comment]
🤣

**Comment by gwil** [comment]
Omg yes! Great find @eudisd  😃

**Comment by lukeed** [comment]
Will merge, just waiting on @gwil to ooh & aah first

**Pull request merged**
